platform: x64
clone_folder: c:\gopath\src\github.com\elves\elvish
environment:
  GOPATH: c:\gopath
  ELVISH_TEST_TIME_SCALE: 10
install:
  # Needed since the codecov uploader depends on a UNIX "find" command.
  - set PATH=C:\msys64\usr\bin;%PATH%
build: off
before_test:
  - go version
test_script:
  - go test -coverprofile=coverage -covermode=set ./...
  - curl -s https://codecov.io/bash -o codecov && bash codecov -f coverage
