platform: x64
clone_folder: c:\gopath\src\github.com\elves\elvish
environment:
  GOPATH: c:\gopath
  ELVISH_TEST_TIME_SCALE: 10
build: off
before_test:
  - go version
test_script:
  - go test -coverprofile=coverage -covermode=set ./...
  - curl -s https://codecov.io/bash -o codecov && bash codecov -f coverage
