platform: x64
clone_folder: c:\gopath\src\github.com\elves\elvish
environment:
  GOPATH: c:\gopath
  ELVISH_TEST_TIME_SCALE: 10
install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\usr\bin;%PATH%
  - go version
  - go env
build_script:
  - make test
deploy_script:
  - make upload-coverage-codecov
