container:
  image: golang:latest
env:
  GOPROXY: https://proxy.golang.org
  CGO_ENABLED: 0
  ELVISH_TEST_UI_TIMEOUT: 5s
test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  test_script: make test
