env:
  ELVISH_TEST_UI_TIMEOUT: 5s
test_task:
  go_modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  matrix:
    - name: Test on Linux
      container:
        image: golang:latest
    - name: Test on Linux (Old Supported Go Version)
      container:
        image: golang:1.13
    - name: Test on macOS
      osx_instance:
        image: catalina-base
      setup_script: brew install go
      env:
        GOPATH: $HOME/go
    - name: Test on FreeBSD
      freebsd_instance:
        image_family: freebsd-12-1
      setup_script: pkg install -y go bash
      env:
        GOPATH: $HOME/go
  go_version_script: go version
  test_script: go test ./...
  upload_coverage_script:
    - go test -coverprofile=coverage -covermode=set ./...
    - curl -s https://codecov.io/bash -o codecov && bash codecov -f coverage
