env:
  GOPROXY: https://proxy.golang.org
  ELVISH_TEST_UI_TIMEOUT: 5s
test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  matrix:
    - container:
        image: golang:latest
    - windows_container:
        image: golang:latest
    - osx_instance:
        image: catalina-base
      setup_script: brew install go
    - freebsd_instance:
        image_family: freebsd-12-1
      setup_script: pkg install -y go
  test_script: go test ./...
