env:
  GOPROXY: https://proxy.golang.org
  CGO_ENABLED: 0
  ELVISH_TEST_UI_TIMEOUT: 5s
test_task:
  matrix:
    - container:
        image: golang:latest
    - windows_container:
        image: golang:latest
    - osx_instance:
        image: catalina-base
    - freebsd_instance:
        image_family: freebsd-12-1
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  test_script: make test
