test_task:
  env:
    ELVISH_TEST_TIME_SCALE: 10
    CODECOV_TOKEN: ENCRYPTED[832ae776d0809c879cb08b78d8ac3cc89cbff90688beafc329661fb42d06d3bc5feef31da156d78fb442e3491468ef6d]
  go_modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  matrix:
    - name: Test on Linux
      container:
        image: golang:latest
    - name: Test on Linux (Old Supported Go Version)
      container:
        image: golang:1.13
    - name: Test on macOS
      osx_instance:
        image: catalina-base
      setup_script: brew install go
      env:
        GOPATH: $HOME/go
    - name: Test on FreeBSD
      freebsd_instance:
        image_family: freebsd-12-1
      setup_script: pkg install -y go bash
      env:
        GOPATH: $HOME/go
  go_version_script: go version
  test_script: go test -race ./...
  upload_coverage_script:
    - go test -coverprofile=coverage -covermode=set ./...
    - curl -s https://codecov.io/bash -o codecov && bash codecov -f coverage -t $CODECOV_TOKEN

deploy_task:
  name: Build binaries and deploy to bintray
  env:
    BINTRAY_TOKEN: ENCRYPTED[1a1820d17a2014de6b1798d379f86aa24bbd8acd5149656a98bfdf33746c78c85fefc8e6e522fedacdf8c4bf92bb25a0]
  go_modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  container:
    image: theelves/cirrus-builder
  go_version_script: go version
  deploy_script: ./tools/cirrus-deploy.sh
