env:
  ELVISH_TEST_UI_TIMEOUT: 5s
test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    # Cannot use $GOPATH here since some of the environments do not have it
    # defined. Fortunately none of them have a custom $GOPATH; they are all
    # equal to $HOME/go.
    folder: $HOME/go/pkg/mod
  matrix:
    - name: Test on Linux
      container:
        image: golang:latest
      env_debug_script: pwd; env
    - name: Test on Windows
      windows_container:
        image: golang:latest
      env_debug_script: set
    - name: Test on macOS
      osx_instance:
        image: catalina-base
      setup_script: brew install go
      env_debug_script: pwd; env
    - name: Test on FreeBSD
      freebsd_instance:
        image_family: freebsd-12-1
      setup_script: pkg install -y go
      env_debug_script: pwd; env
  go_env_debug_script: go version; go env
  test_script: go test ./...
