env:
  ELVISH_TEST_UI_TIMEOUT: 5s
test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  matrix:
    - name: Test on Linux
      container:
        image: golang:latest
    - name: Test on Windows
      windows_container:
        image: golang:latest
    - name: Test on macOS
      osx_instance:
        image: catalina-base
      setup_script: brew install go
      env:
        GOPATH: $HOME/go
    - name: Test on FreeBSD
      freebsd_instance:
        image_family: freebsd-12-1
      setup_script: pkg install -y go
      env:
        GOPATH: $HOME/go
  go_version_script: go version
  test_script: go test ./...
