coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch: off
comment: false
ignore:
  # Exclude test helpers from coverage calculation.
  - "pkg/cli/clitest"
  - "pkg/eval/evaltest"
  - "pkg/prog/progtest"
  - "pkg/store/storetest"
  - "pkg/testutil/must.go"
