image: golang:alpine

variables:
  REPO_NAME: gitlab.com/elves/elvish

before_script:
  - go version

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apk add gcc musl-dev
    - go test -race ./...

deploy:
  stage: deploy
  script:
    - apk add zip
    - ./tools/buildall.sh . _bin HEAD
  artifacts:
    paths:
      - _bin
