language: go
os:
  - linux
  - osx
sudo: false
go:
  - 1.14.x
  - 1.13.x
env:
  global:
    - CGO_ENABLED=0
    - ELVISH_TEST_TIME_SCALE=10
jobs:
  include:
    - stage: deploy
      name: Build and upload binaries to bintray
      script: make binaries-travis
      if: type = push
script: make test
