language: go
os:
  - linux
  - osx
sudo: false
go:
  - 1.13.x
  - 1.12.x
env:
  global:
    - CGO_ENABLED=0
    - ELVISH_TEST_UI_TIMEOUT=5s
  jobs:
    - GO111MODULE=off
    - GO111MODULE=on
jobs:
  include:
    # NOTE: Coverages are not enabled for pull requests yet
    - stage: deploy
      name: Generate and upload coverage to codecov and coveralls
      script: make upload-coverage-codecov upload-coverage-coveralls
      if: type = push
      os: linux
    - name: Generate and upload coverage to codecov
      script: make upload-coverage-codecov
      if: type = push
      os: osx
    - name: Build and upload binaries to bintray
      script: make binaries-travis
      if: type = push AND branch = master
script: make test
